### ISSUE TITLE
Player names not available

### ISSUE THREAD

**Issue by energywave** [jdeath/Bedrock-Homeassistant#1]
First thank you very much! This integration works beautifully.
But I'm missing online player names. The core integration doc says they're exposed as attributes in the online players sensor. But with bedrock server there aren't.
Can this be implemented?

**Comment by jdeath** [comment]
Unfortunately not right now. The mcstatus package only provides player names on Java, not on bedrock. If mcstatus (https://github.com/Dinnerbone/mcstatus/) is updated with this capability, then I could update this integration to show them.

**Comment by Kirbo** [comment]
I think this is supported now, or am I incorrect? https://github.com/Dinnerbone/mcstatus/issues/158
Also noticed that mcstatus supports Bedrock servers now as well, should this make any difference for this project: https://github.com/Dinnerbone/mcstatus/issues/153

**Comment by jdeath** [comment]
Player names are just for Java, not bedrock. This home assistant integration uses and has always used mcstatus (albeit an older version), just like the built JAVA only one. Since the built-in homeassistant uses an old version, it is a pain to do a pull request to get them to update. I will do that when/if mcstatus is ever updated to handle playernames.
